# Generated by Django 4.2.11 on 2024-03-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choice_category',
            field=models.CharField(choices=[('SC', 'Science'), ('TC', 'Technology'), ('EC', 'Economy'), ('SP', 'Sport')], default='Science', max_length=4),
        ),
    ]
